protected/models/Contact.php
<?php

/**
 * Created by PhpStorm.
 * User: david
 * Date: 20/01/17
 * Time: 12:23 PM
 */
class Contact extends DbModel
{
    public $id;
    public $first_name;
    public $last_name;

    public function rules()
    {
        return [
            'id' => [
                'primary' => true,
                'autoIncrement' => true
            ],
            'first_name' => [
                'required' => true
            ],
            'last_name' => [
                'required' => false
            ]
        ];
    }

    public function tableName() {
        return 'contact';
    }
}

protected/controllers/AboutController.php
<?php

/**
 * Created by PhpStorm.
 * User: david
 * Date: 19/01/17
 * Time: 2:40 PM
 */
class AboutController extends ControllerBase
{

}

protected/controllers/ContactController.php
<?php

/**
 * Created by PhpStorm.
 * User: david
 * Date: 19/01/17
 * Time: 2:39 PM
 */
class ContactController extends ControllerBase
{
    public function actionIndex()
    {
        $this->render('index');
    }

    public function actionSave() {

        if (empty($_POST["contact"]))
            throw new OpRoutingException("missing form");

        $contact = new Contact();
        $contact->setAttributes($_POST["contact"]);

        if ($contact->hasErrors()) {
            http_response_code(400);
            echo json_encode($contact->errors());
            return;
        }

        $contact->save();
        echo json_encode($contact);
    }

    public function actionList(){
        $contact = new Contact();
        $contacts = $contact->readAll();

        $this->render('list', ['models' => $contacts]);
    }
}

protected/controllers/ErrorController.php
<?php

/**
 * Created by PhpStorm.
 * User: david
 * Date: 19/01/17
 * Time: 3:14 PM
 */
class ErrorController extends ControllerBase
{
    public function actionIndex($errorCode, $errorMessage) {
        http_response_code(404);
        echo ltrim("{$errorCode} {$errorMessage}", '0 ');
    }
}

protected/controllers/SiteController.php
<?php

/**
 * Created by PhpStorm.
 * User: david
 * Date: 19/01/17
 * Time: 2:42 PM
 */
class SiteController extends ControllerBase
{

}

protected/views/contact/index.php
<form id="contact-form" method="post">

    First Name
    <br>
    <input type="text" name="contact[first_name]" />
    <span style="color: red" data-field-name="contact[first_name]"></span>
    <br>

    LastName
    <br>
    <input type="text" name="contact[last_name]" />
    <span style="color: red" data-field-name="contact[last_name]"></span>
    <br>

    <input type="submit" value="save" />
</form>


<script>
    var $contactForm = $('#contact-form');
    $contactForm.submit(function(e) {
        e.preventDefault();

        var formData = $(this).serialize();

        /* old fashions
        $.ajax({
            type: 'POST',
            url: '/contact/save',
            dataType: 'json',
            data: formData,
            success: function(result) {
                console.log(result);
            },
            error: function(xhr) {
                console.log(xhr);
            },
            complete: function() {

            }
        });*/

        var promise = $.ajax({
            type: 'POST',
            url: '/contact/save',
            dataType: 'json',
            data: formData
        });

        promise
            .then(function(result) {

            })
            .fail(function(xhr) {
                try {
                    var errors = JSON.parse(xhr.responseText);
                    $.each(errors, function(attr, errors) {

                        var mergeStringArrayReduceCallBack = function(prev, next) {
                            return prev + ' ' + next;
                        };

                        var errorSummaryOfField = errors.reduce(mergeStringArrayReduceCallBack, '');

                       $('[data-field-name="contact[' + attr + ']"]').html(errorSummaryOfField);
                    });
                } catch(e) {

                }
            })
            .always(function() {

            });
    });
</script>

protected/views/contact/list.php
<ul>
<?php foreach($models as $model) :?>
    <li><?= $model->first_name; ?> <?= $model->last_name; ?></li>
<?php endforeach; ?>
</ul>

protected/views/layouts/main.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Op madafaka</title>

        <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    </head>

    <body>
        <h1>Op is cool op is da bomb</h1>


        <div>
            <?= $content ?>
        </div>


        <h1>Footer is cool footer is awesome</h1>
    </body>
</html>